In [1]:
# Import modules

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
# Import dataset as dataframe

heart = pd.read_csv("heart.csv")

In [3]:
# Splitting of data - 75% for training data and 25% for test data
# Importing the train_test_split

from sklearn.model_selection import train_test_split

In [4]:
from sklearn.preprocessing import StandardScaler


# Variable target
Y = heart.target.values

# Variable prediction
x = heart.drop(['target'], axis = 1)


In [5]:
# Standardizing the features
X = StandardScaler().fit_transform(x)

C:\Users\Marcos Rocha\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Marcos Rocha\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [6]:
# Setting split rate
split_test_size = 0.25

In [7]:
# Creating test data and train data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = split_test_size, random_state = 42)

In [8]:
# Building and Trainning Classification Model

# Importing Classifier modules
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [9]:
model_KNN = KNeighborsClassifier()
model_KNN.fit(X_train, Y_train.ravel())
KNN_predict_test = model_KNN.predict(X_test)
    
acc_KNN = accuracy_score(Y_test, KNN_predict_test)
print(acc_KNN)
print(confusion_matrix(Y_test, KNN_predict_test))

0.8947368421052632
[[31  4]
 [ 4 37]]


In [13]:
model_DT = DecisionTreeClassifier()
model_DT.fit(X_train, Y_train.ravel())
DT_predict_test = model_DT.predict(X_test)

acc_DT = accuracy_score(Y_test, DT_predict_test)
print(acc_DT)
print(confusion_matrix(Y_test, DT_predict_test))

0.7631578947368421
[[28  7]
 [11 30]]


In [12]:
model_XG = GradientBoostingClassifier()
model_XG.fit(X_train, Y_train.ravel())
XG_predict_test = model_XG.predict(X_test)

acc_XG = accuracy_score(Y_test, XG_predict_test)
print(acc_XG)
print(confusion_matrix(Y_test, XG_predict_test))

0.7631578947368421
[[26  9]
 [ 9 32]]


In [14]:
model_RF = RandomForestClassifier()
model_RF.fit(X_train, Y_train.ravel())
RF_predict_test = model_RF.predict(X_test)

acc_RF = accuracy_score(Y_test, RF_predict_test)
print(acc_RF)
print(confusion_matrix(Y_test, RF_predict_test))

0.868421052631579
[[31  4]
 [ 6 35]]


C:\Users\Marcos Rocha\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
